/*
  ==============================================================================

	This file was auto-generated by the Introjucer!

	It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "Main.h"
#include "PackageHandler.h"

File thePresetFolder;
START_JUCE_APPLICATION (SequencerApplication)

void SequencerApplication::initialise (const String& commandLine)
{
	thePackageHandler = new PackageHandler();
	theSequencerMaster = new Master();
	mainWindow = new MainWindow(theSequencerMaster->getMasterTree());
}

void SequencerApplication::updateCallback()
{
	startTimer(1000);
}
void SequencerApplication::timerCallback()
{
	delete thePackageHandler;
	stopTimer();
}