/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

class SequencerAudioProcessorEditor  : public AudioProcessorEditor, public SliderListener
{
public:
    SequencerAudioProcessorEditor (SequencerAudioProcessor* ownerFilter);
    ~SequencerAudioProcessorEditor();

    void paint (Graphics& g);
	void sliderValueChanged(Slider* slider);
	void resized();
private:
	
	OwnedArray<Slider> theStepSliders;
};


#endif  // PLUGINEDITOR_H_INCLUDED
