/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
SequencerAudioProcessorEditor::SequencerAudioProcessorEditor (SequencerAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter)
{
	for(int i=0;i<NUM_CHANNELS_MAX;i++)
	{
		addAndMakeVisible(theStepSliders.add(new Slider("Step" + String(i))));
		theStepSliders[i]->setSliderStyle (Slider::LinearBarVertical);
		theStepSliders[i]->addListener (this);
		theStepSliders[i]->setRange (-12, 12, 1);
	}
	
    setSize (400, 300);
}

SequencerAudioProcessorEditor::~SequencerAudioProcessorEditor()
{
}

void SequencerAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!",
                      0, 0, getWidth(), getHeight(),
                      Justification::centred, 1);
}

void SequencerAudioProcessorEditor::sliderValueChanged(Slider* slider)
{
	
}

void SequencerAudioProcessorEditor::resized()
{
	for(int i=0;i<NUM_CHANNELS_MAX;i++)
	{
		theStepSliders[i]->setBounds(10 + 10*i, 20, 50, 100);
	}
}






